sudo: required
services:
    - docker
language: c
env:
    - AULA_IMAGE=quay.io/liqd/aula:thentos-0.8 AULA_SOURCE=/liqd/aula

before_install:
    - grep '\(MemTotal\|SwapTotal\)' /proc/meminfo
    - git show | head -1  # (for matching against commit hash given on the travis log web page)
    - docker pull $AULA_IMAGE

script:
    - docker run --rm -it -v `pwd`:$AULA_SOURCE $AULA_IMAGE /bin/sh -c "$AULA_SOURCE/.travis/docker-hlint.sh"
    - docker run --rm -it -v `pwd`:$AULA_SOURCE $AULA_IMAGE /bin/sh -c "$AULA_SOURCE/.travis/docker-build.sh --qc-max-success 1000 --qc-max-size 150"

#after_script:
#    - docker run -e "TRAVIS=$TRAVIS" -e "TRAVIS_JOB_ID=$TRAVIS_JOB_ID" --rm -it -v `pwd`:$AULA_SOURCE $AULA_IMAGE /bin/sh -c "$AULA_SOURCE/.travis/docker-coveralls.sh"

notifications:
    email: false
    irc:
        channels:
            - "irc.freenode.net#thentos"
        template: "%{branch}/%{author}: %{message}"
        on_pull_requests: true
