sudo: required
services:
    - docker
language: c
env:
    - AULA_IMAGE=quay.io/liqd/aula

before_install:
    - grep '\(MemTotal\|SwapTotal\)' /proc/meminfo
    - git show | head -1  # (for matching against commit hash given on the travis log web page)
    - docker pull $AULA_IMAGE
    - docker run --rm -it -v `pwd`:/root/aula/ $AULA_IMAGE /bin/sh -c "/root/aula/.travis/docker-list-sandbox-packages.sh"

script:
    - docker run --rm -it -v `pwd`:/root/aula/ $AULA_IMAGE /bin/sh -c "/root/aula/.travis/docker-hlint.sh"
    - docker run --rm -it -v `pwd`:/root/aula/ $AULA_IMAGE /bin/sh -c "/root/aula/.travis/docker-build.sh"

after_script:
    - docker run -e "TRAVIS=$TRAVIS" -e "TRAVIS_JOB_ID=$TRAVIS_JOB_ID" --rm -it -v `pwd`:/root/aula/ $AULA_IMAGE /bin/sh -c "/root/aula/.travis/docker-coveralls.sh"


notifications:
    email: false
    irc:
        channels:
            - "irc.freenode.net#thentos"
        template: "%{branch}/%{author}: %{message}"
        on_pull_requests: true
