name:        aula
version:     0.37.0
license:     AGPL
copyright:   2016-2017 liquid democracy e.V. Berlin
author: >
  Andor Penzes <andor.penzes@liqd.de>,
  Andres Löh <andres@well-typed.com>,
  Caroline Clifford <caroline.clifford@liqd.de>,
  Matthias Fischmann <mf@zerobuzz.net>,
  Mikolaj Konarski <mikolaj@well-typed.com>,
  Nicolas Pouillard <np@nicolaspouillard.fr>
maintainer:  matthias.fischmann@liqd.net
github:      liqd/aula
category:    Web

data-files:
    - README.md
    - docs/*
    - scripts/*
    - docker/*
    - default-avatars/*
    - static/*
    - static/css/*
    - static/fonts/*
    - static/icons/*
    - static/images/*
    - static/js/*
    - static/svg/*
    - static/templates/*
    - static/third-party/modernizr/modernizr-custom.js
    - static/third-party/showdown/dist/*
    - static/third-party/d3/d3.*js
    - null-terms-of-use.md

ghc-options: -Wall -with-rtsopts=-T

dependencies:
    - base >=4.8 && <4.9
    - thentos-cookie-session >=0.9.1 && <0.10
    - aeson
    - aeson-pretty
    - aeson-qq
    - acid-state >=0.14
    - basic-sop
    - binary
    - bytestring
    - case-insensitive
    - cassava >= 0.4.5.0
    - containers
    - cookie
    - cryptonite >=0.6 && <0.16
    - css-syntax
    - digestive-functors
    - digestive-functors-lucid
    - directory
    - ekg
    - ekg-core
    - elocrypt >=0.4.1 && <0.5
    - email-validate
    - filepath
    - functor-infix
    - generic-aeson
    - generics-sop
    - tagsoup >=0.13.10
    - http-client
    - http-media
    - http-types
    - JuicyPixels >=3.2.6.2 && <3.3
    - lens
    - lucid
    - mime-mail
    - mtl
    - parsec
    - pretty-show
    - process
    - QuickCheck
    - quickcheck-instances
    - random
    - safecopy
    - scrypt
    - servant >=0.7 && <0.8
    - servant-lucid >=0.7 && <0.8
    - servant-server >=0.7 && <0.8
    - stm
    - string-conversions
    - template-haskell
    - text
    - text-icu
    - time
    - transformers
    - unicode-properties
    - unicode-transforms >= 0.3.3
    - vector
    - wai
    - wai-app-static
    - wai-middleware-metrics
    - warp
    - xlsx
    - xlsx-templater
    - yaml
    - zip-archive

library:
  source-dirs: src
  other-modules:
    - Paths_aula

executables:
  aula-server:
    main: Aula.hs
    source-dirs: exec
    other-modules:
    dependencies:
      - aula

  aula-migrate:
    main: AulaMigrate.hs
    source-dirs: exec
    other-modules:
    dependencies:
      - aula

  aula-html-dummies:
    main: RenderHtml.hs
    source-dirs: exec
    other-modules:
    dependencies:
      - aula
      - extra
      - fsnotify
      - hspec

  aula-avatars:
    main: ResizeAvatar.hs
    source-dirs: exec
    other-modules:
    dependencies:
      - aula

  aula-i18n:
    main: I18N.hs
    source-dirs: exec
    other-modules:
    dependencies:
      - aula
      - aeson-extra
      - unordered-containers

  aula-init-state:
    main: InitState.hs
    source-dirs: exec
    other-modules:
    dependencies:
      - aula

  aula-reset-all-passwords:
    main: ResetAllPasswords.hs
    source-dirs: exec
    other-modules:
    dependencies:
      - aula

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests
    dependencies:
      - aula
      - base >=4.8 && <4.9
      - binary >= 0.7.5 && <0.8
      - digestive-functors >= 0.8 && <0.9
      - free
      - hspec
      - hspec-core
      - hspec-wai
      - HUnit >= 1.3
      - lens
      - lucid
      - mtl
      - QuickCheck >= 2.8 && <2.9
      - servant-mock >=0.7 && <0.8
      - servant-server
      - string-conversions
      - temporary >=1.2.0.3 && <1.3
      - text
      - unordered-containers
      - wai-extra
      - wreq
      - webdriver
