name:        aula
version:     0.8.0
license:     AGPL
copyright:   2016-2017 liquid democracy e.V. Berlin
author: >
  Andor Penzes <andor.penzes@liqd.de>,
  Andres Löh <andres@well-typed.com>,
  Caroline Clifford <caroline.clifford@liqd.de>,
  Matthias Fischmann <mf@zerobuzz.net>,
  Mikolaj Konarski <mikolaj@well-typed.com>,
  Nicolas Pouillard <np@nicolaspouillard.fr>
maintainer:  matthias.fischmann@liqd.net
github:      liqd/aula
category:    Web

ghc-options: -Wall

dependencies:
    - base >=4.8 && <4.9
    - thentos-core >=0.5.0
    - aeson
    - aeson-pretty
    - acid-state >=0.14
    - basic-sop
    - binary
    - bytestring
    - case-insensitive
    - cassava >= 0.4.5.0
    - containers
    - cookie
    - digestive-functors
    - digestive-functors-lucid
    - directory
    - elocrypt >=0.4.1 && <0.5
    - email-validate
    - filepath
    - functor-infix
    - generic-aeson
    - generics-sop
    - http-client
    - http-media
    - http-types
    - lens
    - lucid
    - mime-mail
    - mtl
    - pretty-show
    - process
    - QuickCheck
    - quickcheck-instances
    - safecopy
    - scrypt
    - servant
    - servant-lucid
    - servant-server
    - stm
    - string-conversions
    - template-haskell
    - text
    - time
    - transformers
    - vector ==0.10.12.3
    - wai
    - wai-app-static
    - warp
    - yaml

library:
  source-dirs: src
  other-modules:
    - Paths_aula

executables:
  aula-server:
    main: Aula.hs
    source-dirs: exec
    other-modules:
    dependencies:
      - aula

  aula-html-dummies:
    main: RenderHtml.hs
    source-dirs: exec
    other-modules:
    dependencies:
      - aula
      - extra
      - fsnotify
      - hspec

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests
    dependencies:
      - aula
      - base >=4.8 && <4.9
      - binary >= 0.7.5 && <0.8
      - digestive-functors >= 0.8 && <0.9
      - free
      - hspec
      - hspec-wai
      - lens
      - lucid
      - mtl
      - QuickCheck >= 2.8 && <2.9
      - servant-mock
      - servant-server
      - string-conversions
      - text
      - wai-extra
      - wreq
